from __future__ import annotations

MAX_RETRIES = 10

ALIGNMENT_MERGE_GAP_SECONDS = 0.35
ALIGNMENT_MAX_UTTERANCE_SECONDS = 12.0
ALIGNMENT_MAX_UTTERANCE_CHARS = 220

TURN_MERGE_GAP_SECONDS = 1.25
TURN_MAX_DURATION_SECONDS = 45.0
TURN_MAX_CHARS = 1200

LOW_CONFIDENCE_THRESHOLD = 0.75
TIMESTAMP_PRECISION = 3
